export class TreeNode {
  val: number;
  left: TreeNode | null;
  right: TreeNode | null;

  constructor(val: number, left?: TreeNode | null, right?: TreeNode | null) {
    this.val = val;
    this.left = left ? left : null;
    this.right = right ? right : null;
  }
}

// generated by gemini 3.1
export function arrayToTree(arr: (number | null)[]): TreeNode | null {
  if (arr.length === 0 || arr[0] === null) return null;

  const root = new TreeNode(arr[0]);
  const queue: TreeNode[] = [root];
  let head = 0;
  let i = 1;

  while (i < arr.length) {
    const currentNode = queue[head++];

    // Process left child
    if (arr[i] !== null) {
      const leftNode = new TreeNode(arr[i] as number);
      currentNode.left = leftNode;
      queue.push(leftNode);
    }
    i++;

    // Process right child
    if (i < arr.length && arr[i] !== null) {
      const rightNode = new TreeNode(arr[i] as number);
      currentNode.right = rightNode;
      queue.push(rightNode);
    }
    i++;
  }

  return root;
}

export function findNode(root: TreeNode | null, val: number): TreeNode | null {
  if (!root) return null;
  if (root.val === val) return root;
  return findNode(root.left, val) || findNode(root.right, val);
}
