// %%

export class ListNode {
  val: number;
  next: ListNode | null;

  constructor(val: number, next?: ListNode | null) {
    this.val = val;
    this.next = next ?? null;
  }
}
export function swapPairs(head: ListNode | null): ListNode | null {
  if (!head || !head.next) return head;

  let dummy = head.next,
    prev: ListNode | null = null;

  while (head?.next) {
    if (prev) prev.next = head.next;

    let nxt: ListNode | null = head.next.next;

    head.next.next = head;
    head.next = nxt;

    prev = head;
    head = nxt;
  }

  return dummy;
}

console.log(swapPairs(arrayToList([1, 2, 3, 4]))); // [2, 1, 4, 3]

// === === === === ===

// generated by gemini 3 pro
export function arrayToList(arr: number[]): ListNode | null {
  if (arr.length === 0) return null;
  const head = new ListNode(arr[0]);
  let current = head;
  for (let i = 1; i < arr.length; i++) {
    current.next = new ListNode(arr[i]);
    current = current.next;
  }
  return head;
}
export function listToArray(head: ListNode | null): number[] {
  const result: number[] = [];
  let current = head;
  while (current !== null) {
    result.push(current.val);
    current = current.next;
  }
  return result;
}
