/**
 * Definition for singly-linked list.
 * class ListNode {
 *     val: number
 *     next: ListNode | null
 *     constructor(val?: number, next?: ListNode | null) {
 *         this.val = (val===undefined ? 0 : val)
 *         this.next = (next===undefined ? null : next)
 *     }
 * }
 */
export function reverseBetween(
  head: ListNode | null,
  left: number,
  right: number,
): ListNode | null {
  let dummy = new ListNode(0, head),
    leftPrev = dummy;

  for (let i = 0; i < left - 1; i++) {
    leftPrev = leftPrev.next!;
  }

  let cur = leftPrev.next,
    prev = null;

  for (let i = right - left + 1; i > 0; i--) {
    let nxt = cur?.next;

    cur!.next = prev;
    prev = cur;
    cur = nxt!;
  }

  leftPrev.next!.next = cur;
  leftPrev.next = prev;

  return dummy.next;
}

// === === === === ===

export class ListNode {
  val: number;
  next: ListNode | null;

  constructor(val: number, next?: ListNode | null) {
    this.val = val;
    this.next = next ?? null;
  }
}

// generated by gemini 3 pro
export function arrayToList(arr: number[]): ListNode | null {
  if (arr.length === 0) return null;
  const head = new ListNode(arr[0]);
  let current = head;
  for (let i = 1; i < arr.length; i++) {
    current.next = new ListNode(arr[i]);
    current = current.next;
  }
  return head;
}
export function listToArray(head: ListNode | null): number[] {
  const result: number[] = [];
  let current = head;
  while (current !== null) {
    result.push(current.val);
    current = current.next;
  }
  return result;
}
